/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.casestudyjava;

/**
 *
 * @author PLPASIG
 */
public class OrderPage extends javax.swing.JFrame {

    /**
     * Creates new form StartingPage
     */
    public OrderPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Burgers");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 340, 200, 40);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Filipino Cousine");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton2);
        jButton2.setBounds(50, 220, 200, 40);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Beverages");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton3);
        jButton3.setBounds(50, 520, 200, 40);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Chickens");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton4);
        jButton4.setBounds(50, 280, 200, 40);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Pastries");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton5);
        jButton5.setBounds(50, 400, 200, 40);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Snacks/Desserts");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton6);
        jButton6.setBounds(50, 460, 200, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\test2.png")); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(890, 620, 50, 50);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\test2.png")); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(670, 620, 50, 50);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\test2.png")); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(410, 620, 50, 50);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("₱ 40.00");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(760, 620, 80, 50);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("₱ 50.00");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(510, 620, 80, 50);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("₱ 50.00");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(290, 620, 80, 50);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("KARE - KARE");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(760, 580, 200, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("CHICKEN KALDERETA");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(510, 580, 200, 40);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("CHICKEN ADOBO");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(290, 580, 250, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\Kalderetang Manok.png")); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(450, 410, 310, 160);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\Chicken Adobo.png")); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(270, 430, 230, 160);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\kare kare.png")); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(730, 420, 250, 170);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\test.png")); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(870, 300, 50, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\test.png")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(520, 300, 50, 50);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("₱ 80.00");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(680, 300, 80, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("₱ 70.00");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 300, 80, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PORK SINIGANG");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(680, 250, 300, 60);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("PORK BICOL EXPRESS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 250, 300, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\tag.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, -30, 260, 180);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\Sinigang na baboy.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(650, 20, 300, 250);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\fsfsfsf\\PorkBicolExpress_1200x1200.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 10, 330, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\OneDrive\\Pictures\\a.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1230, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
